### ISSUE TITLE
Wrong project uploaded

### ISSUE THREAD

**Issue by spvreddy** [arif98741/pos#3]
Uploaded template was different

**Comment by arif98741** [comment]
what do you mean by wrong?

**Comment by spvreddy** [comment]
The project you mentioned in http://phpdark.com/project/point-of-sale/ is completely different from what you uploaded.

**Comment by arif98741** [comment]
Sorry the project directory is changed
use  **http://phpdark.com/pos**

**Comment by spvreddy** [comment]
Can you please link to download this one.UI and visibility looks good
http://phpdark.com/pos/index.php

**Comment by arif98741** [comment]
Sry bro. The online version is premium. It is using in the market now. Here Github version is available for free use. If you need any help to make a project like this. I will try my best to complete.
